export const paletteList = [
    {
      index: 1,
      name: "Green clair",
      "--color-primary-light": "#49a078",
      "--color-secondary-light": "#9cc5a1",
      "--color-tertiary-light": "#216869",
      "--color-accent-light": "#ED9555",
      "--color-info-light": "#82b4ff",
      "--color-success-light": "#b0edb5",
      "--color-alert-light": "#fff382",
      "--color-error-light": "#ff829b",
      "--color-background-light": "#dce1de",
      "--color-background-secondary-light": "#e6eae7",
      "--color-text-light": "#1f2421",
      "--color-primary-dark": "#2e3333",
      "--color-secondary-dark": "#4f5552",
      "--color-tertiary-dark": "#777f77",
      "--color-accent-dark": "#A19085",
      "--color-info-dark": "#4da3d5",
      "--color-success-dark": "#b0edb5",
      "--color-alert-dark": "#f4e2ae",
      "--color-error-dark": "#f9c8e8",
      "--color-background-dark": "#171717",
      "--color-background-secondary-dark": "#161917",
      "--color-text-dark": "#9b9b9b",
    },
    {
      index: 2,
      name: "Purple Paradise",
      "--color-primary-light": "#A37BFD",
      "--color-secondary-light": "#D1B0FF",
      "--color-tertiary-light": "#8254E6",
      "--color-accent-light": "#FF8DFB",
      "--color-info-light": "#8080FF",
      "--color-success-light": "#A5F7D9",
      "--color-alert-light": "#FFDDA1",
      "--color-error-light": "#FF827B",
      "--color-background-light": "#F1E9FF",
      "--color-background-secondary-light": "#F5F2FF",
      "--color-text-light": "#1F1D2B",
      "--color-primary-dark": "#443A64",
      "--color-secondary-dark": "#6A5980",
      "--color-tertiary-dark": "#3E3059",
      "--color-accent-dark": "#9F5AFF",
      "--color-info-dark": "#4040A0",
      "--color-success-dark": "#7DE8C2",
      "--color-alert-dark": "#FFB565",
      "--color-error-dark": "#D75754",
      "--color-background-dark": "#18131F",
      "--color-background-secondary-dark": "#1D1826",
      "--color-text-dark": "#A6A6A6",
    },
    {
      index: 3,
      name: "Sunny Yellow",
      "--color-primary-light": "#FFC726",
      "--color-secondary-light": "#FFE273",
      "--color-tertiary-light": "#FFB816",
      "--color-accent-light": "#FFC34A",
      "--color-info-light": "#A3C9FF",
      "--color-success-light": "#9EFFC1",
      "--color-alert-light": "#FFDD86",
      "--color-error-light": "#FF8282",
      "--color-background-light": "#FFF6E0",
      "--color-background-secondary-light": "#FFF8EC",
      "--color-text-light": "#333333",
      "--color-primary-dark": "#5E4C16",
      "--color-secondary-dark": "#9E8529",
      "--color-tertiary-dark": "#734D15",
      "--color-accent-dark": "#997D32",
      "--color-info-dark": "#667CB2",
      "--color-success-dark": "#6FCE96",
      "--color-alert-dark": "#D4B261",
      "--color-error-dark": "#B25555",
      "--color-background-dark": "#1F1F1F",
      "--color-background-secondary-dark": "#252525",
      "--color-text-dark": "#B3B3B3",
    },
    {
      index: 4,
      name: "Ocean Blue",
      "--color-primary-light": "#0086D6",
      "--color-secondary-light": "#5CC2FF",
      "--color-tertiary-light": "#005DAF",
      "--color-accent-light": "#FF9E00",
      "--color-info-light": "#64CFFF",
      "--color-success-light": "#00C78C",
      "--color-alert-light": "#FFD65C",
      "--color-error-light": "#FF5C5C",
      "--color-background-light": "#E5F4FF",
      "--color-background-secondary-light": "#F1F9FF",
      "--color-text-light": "#2B2B2B",
      "--color-primary-dark": "#0E2A3B",
      "--color-secondary-dark": "#385A7D",
      "--color-tertiary-dark": "#0B3859",
      "--color-accent-dark": "#D97E00",
      "--color-info-dark": "#427BA1",
      "--color-success-dark": "#009671",
      "--color-alert-dark": "#D99E00",
      "--color-error-dark": "#B20000",
      "--color-background-dark": "#101820",
      "--color-background-secondary-dark": "#172A3A",
      "--color-text-dark": "#8F8F8F",
    },
    {
      index: 5,
      name: "Pink Delight",
      "--color-primary-light": "#FF5DAE",
      "--color-secondary-light": "#FF9AC2",
      "--color-tertiary-light": "#FF4585",
      "--color-accent-light": "#FFB46D",
      "--color-info-light": "#4AA6FF",
      "--color-success-light": "#9EFFC1",
      "--color-alert-light": "#FFA36D",
      "--color-error-light": "#FF5D5D",
      "--color-background-light": "#FCE8F2",
      "--color-background-secondary-light": "#FEEFF7",
      "--color-text-light": "#33272B",
      "--color-primary-dark": "#54192D",
      "--color-secondary-dark": "#7F3B57",
      "--color-tertiary-dark": "#581A36",
      "--color-accent-dark": "#995923",
      "--color-info-dark": "#22417A",
      "--color-success-dark": "#6FCE96",
      "--color-alert-dark": "#D97E3C",
      "--color-error-dark": "#B20000",
      "--color-background-dark": "#1F1418",
      "--color-background-secondary-dark": "#26161D",
      "--color-text-dark": "#A6A6A6",
    },
    {
      index: 6,
      name: "Nature Green",
      "--color-primary-light": "#00A45F",
      "--color-secondary-light": "#2CC97E",
      "--color-tertiary-light": "#008A49",
      "--color-accent-light": "#FFB800",
      "--color-info-light": "#53A1FF",
      "--color-success-light": "#A4FF96",
      "--color-alert-light": "#FFD745",
      "--color-error-light": "#FF5353",
      "--color-background-light": "#EDF7ED",
      "--color-background-secondary-light": "#F3FDF3",
      "--color-text-light": "#212529",
      "--color-primary-dark": "#10341E",
      "--color-secondary-dark": "#235F38",
      "--color-tertiary-dark": "#0F3A1C",
      "--color-accent-dark": "#9B7D00",
      "--color-info-dark": "#2952A6",
      "--color-success-dark": "#6EAD71",
      "--color-alert-dark": "#D99F1C",
      "--color-error-dark": "#9F1C1C",
      "--color-background-dark": "#101B11",
      "--color-background-secondary-dark": "#17241A",
      "--color-text-dark": "#A6A6A6",
    },
    {
      index: 7,
      name: "Golden Sands",
      "--color-primary-light": "#FFA800",
      "--color-secondary-light": "#FFC845",
      "--color-tertiary-light": "#FF9300",
      "--color-accent-light": "#FFD55C",
      "--color-info-light": "#446BB0",
      "--color-success-light": "#B2FFEB",
      "--color-alert-light": "#FFC573",
      "--color-error-light": "#FF5C5C",
      "--color-background-light": "#FDF5E5",
      "--color-background-secondary-light": "#FEF9EB",
      "--color-text-light": "#333333",
      "--color-primary-dark": "#4D3500",
      "--color-secondary-dark": "#7A5824",
      "--color-tertiary-dark": "#503900",
      "--color-accent-dark": "#997C2D",
      "--color-info-dark": "#2E4B80",
      "--color-success-dark": "#7DE8C2",
      "--color-alert-dark": "#D9A756",
      "--color-error-dark": "#B20000",
      "--color-background-dark": "#1F1B16",
      "--color-background-secondary-dark": "#25211C",
      "--color-text-dark": "#A6A6A6",
    },
    {
      index: 8,
      name: "Aqua Blue",
      "--color-primary-light": "#00B8D8",
      "--color-secondary-light": "#80E8FF",
      "--color-tertiary-light": "#007F9D",
      "--color-accent-light": "#FF8E00",
      "--color-info-light": "#A6CBFF",
      "--color-success-light": "#A4FF96",
      "--color-alert-light": "#FFC845",
      "--color-error-light": "#FF5353",
      "--color-background-light": "#F0F9FF",
      "--color-background-secondary-light": "#F6FDFF",
      "--color-text-light": "#2B2B2B",
      "--color-primary-dark": "#002C39",
      "--color-secondary-dark": "#405C69",
      "--color-tertiary-dark": "#002330",
      "--color-accent-dark": "#D97C00",
      "--color-info-dark": "#7B9CB3",
      "--color-success-dark": "#6EAD71",
      "--color-alert-dark": "#D99F1C",
      "--color-error-dark": "#9F1C1C",
      "--color-background-dark": "#111F24",
      "--color-background-secondary-dark": "#192B30",
      "--color-text-dark": "#8F8F8F",
    },
    {
      index: 9,
      name: "Sunset Orange",
      "--color-primary-light": "#FF5714",
      "--color-secondary-light": "#FF8D62",
      "--color-tertiary-light": "#FF4500",
      "--color-accent-light": "#FF9E00",
      "--color-info-light": "#84A4FF",
      "--color-success-light": "#A4FF96",
      "--color-alert-light": "#FFB365",
      "--color-error-light": "#FF5353",
      "--color-background-light": "#FFF1E6",
      "--color-background-secondary-light": "#FFFAF5",
      "--color-text-light": "#33251E",
      "--color-primary-dark": "#4D1600",
      "--color-secondary-dark": "#7A432E",
      "--color-tertiary-dark": "#501200",
      "--color-accent-dark": "#995200",
      "--color-info-dark": "#5C76B2",
      "--color-success-dark": "#6EAD71",
      "--color-alert-dark": "#D98249",
      "--color-error-dark": "#9F1C1C",
      "--color-background-dark": "#1F1611",
      "--color-background-secondary-dark": "#261E19",
      "--color-text-dark": "#A6A6A6",
    },
    {
      index: 10,
      name: "Mystic Purple",
      "--color-primary-light": "#AC51FF",
      "--color-secondary-light": "#D29DFF",
      "--color-tertiary-light": "#8A38FF",
      "--color-accent-light": "#FFA7FF",
      "--color-info-light": "#7988FF",
      "--color-success-light": "#9EFFC1",
      "--color-alert-light": "#FF9D9D",
      "--color-error-light": "#FF5353",
      "--color-background-light": "#F8F4FF",
      "--color-background-secondary-light": "#FCFAFF",
      "--color-text-light": "#2B2B2B",
      "--color-primary-dark": "#3C1E59",
      "--color-secondary-dark": "#634C7F",
      "--color-tertiary-dark": "#361B50",
      "--color-accent-dark": "#D97BD9",
      "--color-info-dark": "#495BA3",
      "--color-success-dark": "#6FCE96",
      "--color-alert-dark": "#D97B7B",
      "--color-error-dark": "#9F1C1C",
      "--color-background-dark": "#131015",
      "--color-background-secondary-dark": "#1A1619",
      "--color-text-dark": "#A6A6A6",
    },
    {
      index: 11,
      name: "Soft Pink",
      "--color-primary-light": "#FF86B3",
      "--color-secondary-light": "#FFB9D7",
      "--color-tertiary-light": "#FF6B94",
      "--color-accent-light": "#FFA0BF",
      "--color-info-light": "#A1D2FF",
      "--color-success-light": "#A4FF96",
      "--color-alert-light": "#FFA788",
      "--color-error-light": "#FF5353",
      "--color-background-light": "#FFF4F7",
      "--color-background-secondary-light": "#FFFAFC",
      "--color-text-light": "#33262C",
      "--color-primary-dark": "#4D2736",
      "--color-secondary-dark": "#7A4A60",
      "--color-tertiary-dark": "#501F2D",
      "--color-accent-dark": "#995771",
      "--color-info-dark": "#6E9DBE",
      "--color-success-dark": "#6EAD71",
      "--color-alert-dark": "#D97769",
      "--color-error-dark": "#9F1C1C",
      "--color-background-dark": "#1F1418",
      "--color-background-secondary-dark": "#26171A",
      "--color-text-dark": "#A6A6A6",
    },
    {
      index: 12,
      name: "Vibrant Yellow",
      "--color-primary-light": "#FFC800",
      "--color-secondary-light": "#FFDC45",
      "--color-tertiary-light": "#FFC100",
      "--color-accent-light": "#FFED66",
      "--color-info-light": "#66AFFF",
      "--color-success-light": "#B2FFEB",
      "--color-alert-light": "#FFD66C",
      "--color-error-light": "#FF5353",
      "--color-background-light": "#FFFAE5",
      "--color-background-secondary-light": "#FFFCF2",
      "--color-text-light": "#333333",
      "--color-primary-dark": "#4D3B00",
      "--color-secondary-dark": "#7A6424",
      "--color-tertiary-dark": "#503800",
      "--color-accent-dark": "#997E2D",
      "--color-info-dark": "#426BA3",
      "--color-success-dark": "#7DE8C2",
      "--color-alert-dark": "#D9A856",
      "--color-error-dark": "#9F1C1C",
      "--color-background-dark": "#1F1B16",
      "--color-background-secondary-dark": "#25211C",
      "--color-text-dark": "#A6A6A6",
    },
    {
      index: 13,
      name: "Elegant Gray",
      "--color-primary-light": "#7B7B7B",
      "--color-secondary-light": "#BEBEBE",
      "--color-tertiary-light": "#5C5C5C",
      "--color-accent-light": "#A1A1A1",
      "--color-info-light": "#A1A1A1",
      "--color-success-light": "#A4FF96",
      "--color-alert-light": "#FFA788",
      "--color-error-light": "#FF5353",
      "--color-background-light": "#F5F5F5",
      "--color-background-secondary-light": "#F9F9F9",
      "--color-text-light": "#1F1F1F",
      "--color-primary-dark": "#4D4D4D",
      "--color-secondary-dark": "#909090",
      "--color-tertiary-dark": "#333333",
      "--color-accent-dark": "#7A7A7A",
      "--color-info-dark": "#7A7A7A",
      "--color-success-dark": "#6EAD71",
      "--color-alert-dark": "#D97769",
      "--color-error-dark": "#9F1C1C",
      "--color-background-dark": "#1F1F1F",
      "--color-background-secondary-dark": "#252525",
      "--color-text-dark": "#A6A6A6",
    },
    {
      index: 14,
      name: "Royal Purple",
      "--color-primary-light": "#6B1D73",
      "--color-secondary-light": "#9E55A2",
      "--color-tertiary-light": "#521548",
      "--color-accent-light": "#A75BAA",
      "--color-info-light": "#536BA1",
      "--color-success-light": "#A4FF96",
      "--color-alert-light": "#FFA788",
      "--color-error-light": "#FF5353",
      "--color-background-light": "#F3F0F8",
      "--color-background-secondary-light": "#F8F6FA",
      "--color-text-light": "#2B2B2B",
      "--color-primary-dark": "#2E0F39",
      "--color-secondary-dark": "#553A5D",
      "--color-tertiary-dark": "#270C2B",
      "--color-accent-dark": "#7F4680",
      "--color-info-dark": "#364A76",
      "--color-success-dark": "#6EAD71",
      "--color-alert-dark": "#D97769",
      "--color-error-dark": "#9F1C1C",
      "--color-background-dark": "#110915",
      "--color-background-secondary-dark": "#1A121B",
      "--color-text-dark": "#A6A6A6",
    },
    {
      index: 15,
      name: "Ocean Blue",
      "--color-primary-light": "#1871B6",
      "--color-secondary-light": "#5DA1D7",
      "--color-tertiary-light": "#0F5081",
      "--color-accent-light": "#4E8FB8",
      "--color-info-light": "#9BC1D7",
      "--color-success-light": "#A4FF96",
      "--color-alert-light": "#FFA788",
      "--color-error-light": "#FF5353",
      "--color-background-light": "#EDF5FA",
      "--color-background-secondary-light": "#F3F9FC",
      "--color-text-light": "#222B38",
      "--color-primary-dark": "#0B405F",
      "--color-secondary-dark": "#305D77",
      "--color-tertiary-dark": "#072B44",
      "--color-accent-dark": "#3B6380",
      "--color-info-dark": "#7293A3",
      "--color-success-dark": "#6EAD71",
      "--color-alert-dark": "#D97769",
      "--color-error-dark": "#9F1C1C",
      "--color-background-dark": "#0F1B22",
      "--color-background-secondary-dark": "#141D22",
      "--color-text-dark": "#A6A6A6",
    },
  ];
  
