export const weatherCodeMapping = {
  0: {
    weatherCondition: "Clear sky",
    imgDay: "DAY_CLEAR",
    imgNightFullMoon: "NIGHT_FM_CLEAR",
    imgNightHalfMoon: "NIGHT_HM_CLEAR",
  },
  1: {
    weatherCondition: "Mainly clear",
    imgDay: "DAY_CLEAR",
    imgNightFullMoon: "NIGHT_FM_CLEAR",
    imgNightHalfMoon: "NIGHT_HM_CLEAR",
  },
  2: {
    weatherCondition: "Partly cloudy",
    imgDay: "DAY_PARTIAL_CLOUD",
    imgNightFullMoon: "NIGHT_FM_PARTIAL_CLOUD",
    imgNightHalfMoon: "NIGHT_FM_PARTIAL_CLOUD",
  },
  3: {
    weatherCondition: "Overcast",
    imgDay: "OVERCAST",
    imgNightFullMoon: "OVERCAST",
    imgNightHalfMoon: "OVERCAST",
  },
  45: {
    weatherCondition: "Fog",
    imgDay: "FOG",
    imgNightFullMoon: "FOG",
    imgNightHalfMoon: "FOG",
  },
  48: {
    weatherCondition: "Rime fog",
    imgDay: "MIST",
    imgNightFullMoon: "MIST",
    imgNightHalfMoon: "MIST",
  },
  51: {
    weatherCondition: "Light drizzle",
    imgDay: "DAY_RAIN",
    imgNightFullMoon: "NIGHT_FM_RAIN",
    imgNightHalfMoon: "NIGHT_HM_RAIN",
  },
  53: {
    weatherCondition: "Moderate drizzle",
    imgDay: "DAY_RAIN",
    imgNightFullMoon: "NIGHT_FM_RAIN",
    imgNightHalfMoon: "NIGHT_HM_RAIN",
  },
  55: {
    weatherCondition: "Dense drizzle",
    imgDay: "DAY_RAIN",
    imgNightFullMoon: "NIGHT_FM_RAIN",
    imgNightHalfMoon: "NIGHT_HM_RAIN",
  },
  56: {
    weatherCondition: "Freezing light drizzle",
    imgDay: "DAY_SLEET",
    imgNightFullMoon: "NIGHT_FM_SLEET",
    imgNightHalfMoon: "NIGHT_HM_SLEET",
  },
  57: {
    weatherCondition: "Freezing dense drizzle",
    imgDay: "DAY_SLEET",
    imgNightFullMoon: "NIGHT_FM_SLEET",
    imgNightHalfMoon: "NIGHT_HM_SLEET",
  },
  61: {
    weatherCondition: "Slight rain",
    imgDay: "DAY_RAIN",
    imgNightFullMoon: "NIGHT_FM_RAIN",
    imgNightHalfMoon: "NIGHT_FM_RAIN",
  },
  63: {
    weatherCondition: "Moderate rain",
    imgDay: "RAIN",
    imgNightFullMoon: "RAIN",
    imgNightHalfMoon: "RAIN",
  },
  65: {
    weatherCondition: "Heavy rain",
    imgDay: "RAIN_THUNDER",
    imgNightFullMoon: "RAIN_THUNDER",
    imgNightHalfMoon: "RAIN_THUNDER",
  },
  66: {
    weatherCondition: "Freezing rain (light)",
    imgDay: "SLEET",
    imgNightFullMoon: "SLEET",
    imgNightHalfMoon: "SLEET",
  },
  67: {
    weatherCondition: "Freezing rain (heavy)",
    imgDay: "SNOW_THUNDER",
    imgNightFullMoon: "SNOW_THUNDER",
    imgNightHalfMoon: "SNOW_THUNDER",
  },
  71: {
    weatherCondition: "Slight snow",
    imgDay: "DAY_SNOW",
    imgNightFullMoon: "NIGHT_FM_SNOW",
    imgNightHalfMoon: "NIGHT_HM_SNOW",
  },
  73: {
    weatherCondition: "Moderate snow",
    imgDay: "SNOW",
    imgNightFullMoon: "NIGHT_FM_SNOW",
    imgNightHalfMoon: "NIGHT_HM_SNOW",
  },
  75: {
    weatherCondition: "Heavy intensity snow",
    imgDay: "SNOW",
    imgNightFullMoon: "NIGHT_FM_SNOW",
    imgNightHalfMoon: "NIGHT_HM_SNOW",
  },
  77: {
    weatherCondition: "Snow grains",
    imgDay: "SLEET",
    imgNightFullMoon: "NIGHT_FM_SLEET",
    imgNightHalfMoon: "NIGHT_HM_SLEET",
  },
  80: {
    weatherCondition: "Slight rain showers",
    imgDay: "DAY_RAIN",
    imgNightFullMoon: "NIGHT_FM_RAIN",
    imgNightHalfMoon: "NIGHT_HM_RAIN",
  },
  81: {
    weatherCondition: "Moderate rain showers",
    imgDay: "RAIN",
    imgNightFullMoon: "RAIN",
    imgNightHalfMoon: "RAIN",
  },
  82: {
    weatherCondition: "Violent rain showers",
    imgDay: "RAIN_THUNDER",
    imgNightFullMoon: "RAIN_THUNDER",
    imgNightHalfMoon: "RAIN_THUNDER",
  },
  85: {
    weatherCondition: "Slight snow showers",
    imgDay: "SNOW",
    imgNightFullMoon: "NIGHT_FM_SNOW",
    imgNightHalfMoon: "NIGHT_HM_SNOW",
  },
  86: {
    weatherCondition: "Heavy rain showers",
    imgDay: "RAIN",
    imgNightFullMoon: "RAIN",
    imgNightHalfMoon: "RAIN",
  },
  95: {
    weatherCondition: "Thunderstorm",
    imgDay: "THUNDER",
    imgNightFullMoon: "THUNDER",
    imgNightHalfMoon: "THUNDER",
  },
  96: {
    weatherCondition: "Thunderstorm with slight hail",
    imgDay: "DAY_SNOW_THUNDER",
    imgNightFullMoon: "NIGHT_FM_SNOW_THUNDER",
    imgNightHalfMoon: "NIGHT_HM_SNOW_THUNDER",
  },
  99: {
    weatherCondition: "Thunderstorm with heavy hail",
    imgDay: "SNOW_THUNDER",
    imgNightFullMoon: "SNOW_THUNDER",
    imgNightHalfMoon: "SNOW_THUNDER",
  },
};